name: kecukupan_sekolah_surabaya
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter  
  flutter_map: ^5.0.0
  flutter_map_marker_cluster: ^1.2.0
  latlong2: ^0.9.0
  flutter_keyboard_visibility: ^5.4.1
  geolocator: ^10.0.0
  http: ^1.1.0
  dio: ^5.3.2  # For HTTP requests
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7  
  flutter_typeahead: ^5.0.0
  permission_handler: ^12.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
